in_fp: data/musedb18hq
target: ${..train_dataset.target}
is_mono: False
sr: 44100
win_size: 3
hop_size: 0.5 # 0.5 optimal according to paper. Must be < win_size
batch_size: 4
# window: 'hann'
window: null